# linux matrix
language: python
os: linux
python:
    - "3.6"
    - "3.5"
    - "3.4"
    - "2.7"

# OSX matrix
matrix:
    include:
        - os: osx
          osx_image: xcode10.1
          language: generic
          env: PYTHON_VERSION=python2
        - os: osx
          osx_image: xcode10.1
          language: generic
          env: PYTHON_VERSION=python3


# System packages
addons:
    apt:
        packages:
            - gfortran
            - libblas3
            - liblapack3
    homebrew:
        packages: 
            - gcc
            - python2
            - python3

# OSX setup
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
      then 
          brew link gcc;
          pip install virtualenv;
          virtualenv venv -p $PYTHON_VERSION;
          source venv/bin/activate;
      fi

install:
    - pip install numpy
    - make
    - python setup.py install
    - pip install -r requirements.txt

# Run tests
script:
    - python run_pypolychord.py; 
