notifications:
  email: false

language: python
python:
- '2.7'

os: linux
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32

install:
- docker pull $DOCKER_IMAGE

script:
- docker run --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build.sh

deploy:
  provider: pypi
  user: guillaume.polychord
  distributions: sdist
  password:
    secure: j7NujNJJIZ8Y6rJR9ALN9ryXbz5nBdoVqcuoiLgb7T2f7CwbJiP5t7ByZaCPSYyBjLVTXrdaI1VKBcUqI8wdnHM+h7x0VM9BYqeQ11MX1jywapO79HC+tv3X0bKBrFb70V8JR4DJtEykogweXMBRoNtPrXajQqeABbRD0PdZz9U64FV/L9BZ52+d0ncSnSfY11V/pHTB0rie/EDEwdyKvTNismTYaoxwuJ6rTxfD/NBqiq/GW0XM5wq5d86ost2POFvSYo8pKwHZxW/kh8MvkEfORlfnRWb3XbSvX1bjMIE8QUJqJBoKpDfPeoG1tP0bvARGB+cQELVgqMkx2XSJyvNIYWT9SeJMOU9OJExPkes9w3PHxJl52/7Ln9wQHJaxA4RDgw21mr5QBOa3kGZG9d8ZnDmuSiG2G/HrL/no0Pb2VsPeQUTbNwci1UsLMvFnAJ0m3RguMPcLUnsPeWFvIYtqrNIS4Yr8tvrpNYPXRjw9kHcWHb2OtTSVun1v4au+mm9pPGIkJRSNKjCya98M4uzjG2Jqm5M4iUaJuBQDfJuV5SOp3mIXz5CEet5ZkHqpp+1E9gIBKwHD0UY3GrAuuDzcAxglbFRDYXKWZbZtYw7/pUog2E/cEtKrP6RUwtxYVWlAhOkKwg8r5zeJPMNFtsqaMS+xbwztQ5lgWCFf1YA=
  skip_existing: true
  on:
    branch: setup_pip
